[connections.snowflake]
account = "GDQCHPL-XKB66364.snowflakecomputing.com"
user = "CHALLA007"
password = "ChaarviChalla@2020"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
role = "SYSADMIN"
